/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evoting1;

import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class Instructions extends javax.swing.JFrame {

    /**
     * Creates new form Instructions
     */
    public Instructions() {
        initComponents();
     jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setOpaque(false);  
        jScrollPane1.setOpaque(false);
   
        jTextArea1.setOpaque(false);
        jTextArea1.setBorder(null);
     jTextArea1.setBackground(new Color(0,0,0,0));
     
    }

    Instructions(String a) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\APSASC 01\\Documents\\NetBeansProjects\\Voting_Aditya\\src\\evoting1\\instructions.png")); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 0, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("                                                   Welcome to the Army Public School E-voting portal\n\n                                             Read the following guidelines before using the Application\n\n 1) If you wish to access the Secret Functions of the Applications, you might as well need a \"Secret Code\", which ,\n    due to security concerns, is known only to the developers.                                                                                            \n\n 2) On prompted to choose the DEFAULT DIRECTORY, Make sure to Select the Folder which Contains the Pictures of all the\n    Candidates in JPEG FORMAT. \n\n 3) It is significant to be particular about the NAMING AND DIMENSIONS of the pictures of candidates.\n    Two methods for Voting have been designed each with its own resources.\n\n     i) INDIVIDUAL VOTING -\n       Naming - Name to be the same as the name registered in the 'ADD/REMOVE CANDIDATES' Menu\n       Dimensions - 250x250 pixels\n\n    ii) MULTIPLE VOTING - \n       Naming - Name to be the same as the name registered in the 'ADD/REMOVE CANDIDATES' Menu with 'S' before the\n       name   (e.g. Name of the Candidate - RAKESH  ; Name of Picture to be - 'SRAKESH')\n       Dimensions - 100x100 pixels \n\n 4) It is most IMPORTANT that you have read and understood all the guidelines.\n\n 5) Stay Tuned and HAPPY VOTING :)\n\n\n                                                                      Developed by Aditya and Abhishek");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 255));
        jButton1.setText("Go to Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(476, 476, 476))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(514, 514, 514)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();

            String comments = "create table location(Location varchar(100));";

            stmt.executeUpdate(comments);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();

            String comments = "create table SecretCode(code varchar(100));";

            stmt.executeUpdate(comments);

            con.close();
            stmt.close();
        } catch (Exception e) {

        }

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();

            String admins = "create table admins(name varchar(20), password varchar(20));";

            stmt.executeUpdate(admins);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();

            String login_info = "create table login_info(name varchar(20), time varchar(20), access varchar(20));";

            stmt.executeUpdate(login_info);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();

            String headboy = "create table headboy(name varchar(20), count int(5));";

            stmt.executeUpdate(headboy);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();

            String headgirl = "create table headgirl(name varchar(20), count int(5));";

            stmt.executeUpdate(headgirl);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }
        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();

            String cultural = "create table cultural(name varchar(20), count int(5));";

            stmt.executeUpdate(cultural);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }

        try {

            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();

            String sports = "create table sports(name varchar(20), count int(5));";

            stmt.executeUpdate(sports);

            con.close();
            stmt.close();

        } catch (Exception e) {

        }

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin"
            );
            Statement stmt = con.createStatement();

            String query = "select *from Location";

            ResultSet rs = stmt.executeQuery(query);

            if (rs.next() != true) {
                JOptionPane.showMessageDialog(null, "Default Path does not exist \nPlease add the Path now");

                JFileChooser browse = new JFileChooser();
                browse.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                int a = browse.showDialog(null, "Save Directory");
                if (a == JFileChooser.APPROVE_OPTION) {
                    File file = browse.getSelectedFile();

                    String path = file.getAbsoluteFile().toString().replace("\\", "/");
                    query = "insert into Location values('" + path + "');";
                    stmt.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Directory Added Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Add the Directory later from Tools Menu");
                }

            }

            con.close();
            rs.close();
            stmt.close();

        } catch (Exception e) {

        }
        JOptionPane.showMessageDialog(null, "Archive has been Created");

        Login login = new Login();
        login.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instructions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
