/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evoting1;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class proceed extends javax.swing.JFrame {

    /**
     * Creates new form proceed
     */
    public proceed() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paney = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namey = new javax.swing.JLabel();
        gogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        paney.setBackground(new java.awt.Color(0, 0, 0));
        paney.setPreferredSize(new java.awt.Dimension(1352, 718));

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evoting1/aas.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Pristina", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Electronic Voting");

        namey.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        namey.setForeground(new java.awt.Color(255, 51, 51));
        namey.setText("A Product Developed by Aditya & Abhishek");

        gogo.setBackground(new java.awt.Color(0, 0, 0));
        gogo.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        gogo.setForeground(new java.awt.Color(255, 255, 153));
        gogo.setText("Proceed");
        gogo.setOpaque(false);
        gogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneyLayout = new javax.swing.GroupLayout(paney);
        paney.setLayout(paneyLayout);
        paneyLayout.setHorizontalGroup(
            paneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneyLayout.createSequentialGroup()
                .addGroup(paneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneyLayout.createSequentialGroup()
                        .addGap(535, 535, 535)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneyLayout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(namey, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneyLayout.createSequentialGroup()
                        .addGap(590, 590, 590)
                        .addComponent(gogo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(405, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(468, 468, 468))
        );
        paneyLayout.setVerticalGroup(
            paneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneyLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(namey, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(gogo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paney, javax.swing.GroupLayout.DEFAULT_SIZE, 1374, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paney, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
paney.requestFocus();
        gogo.setVisible(false);
        namey.setText("");

        Thread t = new Thread() {
            @Override
            public void run() {
                ImageIcon icon = new ImageIcon("src/evoting1/res/kjh.jpg");
                ImageIcon blank = new ImageIcon("src/evoting1/res/aas.png");
                try {
                    pic.setIcon(icon);
                    Thread.sleep(100);
                    pic.setIcon(blank);
                    Thread.sleep(100);
                    pic.setIcon(icon);
                    Thread.sleep(100);
                    pic.setIcon(blank);
                    Thread.sleep(100);
                    pic.setIcon(icon);
                    sleep(100);

                    String text = "A Product Developed by Aditya & Abhishek";
                    String temp = text;
                    String print = "";

                    namey.setText("");

                    while (temp.length() > 0) {
                        if (temp.substring(0, 1).equals(" ")) {
                            print = print + temp.substring(0, 2);
                            temp = temp.substring(2, temp.length());
                        } else {
                            print = print + temp.substring(0, 1);
                            temp = temp.substring(1, temp.length());
                        }
                        sleep(100);
                        namey.setText(print);
                    }
                    sleep(100);
                    namey.setText("A Product Developed by Aditya & Abhishek");
                    sleep(2000);
                    gogo.setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(proceed.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        t.start();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void gogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gogoActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();
            String loc = "create table location(Location varchar(200));";
            stmt.executeUpdate(loc);
            con.close();
            stmt.close();
        } catch (Exception e) {
        }

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();
            String adm = "create table admins(name varchar(200),password varchar(100));";
            stmt.executeUpdate(adm);
            con.close();
            stmt.close();
        } catch (Exception e) {
        }

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();
            String loginf = "create table login_info(name varchar(100),time varchar(20),access varchar(20));";
            stmt.executeUpdate(loginf);
            con.close();
            stmt.close();
        } catch (Exception e) {
        }

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();
            String headboi = "create table headboy(name varchar(50),count int(6));";
            stmt.executeUpdate(headboi);
            con.close();
            stmt.close();
        } catch (Exception e) {
        }

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();
            String headgirly = "create table headgirl(name varchar(50),count int(6));";
            stmt.executeUpdate(headgirly);
            con.close();
            stmt.close();
        } catch (Exception e) {
        }

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();
            String cult = "create table cultural(name varchar (50), count int(6));";
            stmt.executeUpdate(cult);
            con.close();
            stmt.close();
        } catch (Exception e) {
        }

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();
            String sport = "create table sports(name varchar(50),count int(6)) ;";
            stmt.executeUpdate(sport);
            con.close();
            stmt.close();
        } catch (Exception e) {
        }

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();
            String query = "select *from location;";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next() != true) {
                JOptionPane.showMessageDialog(null, "Default Directory does not exist \nPlease add the Path now");
                JFileChooser browse = new JFileChooser();
                browse.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                int a = browse.showDialog(null, "Save Directory");
                if (a == JFileChooser.APPROVE_OPTION) {
                    File file = browse.getSelectedFile();
                    String path = file.getAbsoluteFile().toString().replace("\\", "/");
                    query = "insert inot location values('" + path + "');";
                    stmt.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Directory Added Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Add the Directory later from Tools Menu");
                }
            }
            con.close();
            rs.close();
            stmt.close();
        } catch (Exception e) {
        }

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx", "root", "admin");
            Statement stmt = con.createStatement();
            String secode = "create table SecretCode(Code varchar(17));";
            stmt.executeUpdate(secode);
            con.close();
            stmt.close();
        } catch (Exception e) {
        }

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/skullx/SecretCode", "root", "admin");
            Statement stmt = con.createStatement();
            String secode = "insert into SecretCode values ('123');";
            stmt.executeQuery(secode);
            con.close();
            stmt.close();
        } catch (Exception e) {
        }
        String a = "Splash1";
        secy s = new secy(a);
        s.setVisible(true);
        this.dispose();

        JOptionPane.showMessageDialog(s, "Archive has been Created");
    }//GEN-LAST:event_gogoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
 /*for(double a=0.0;a<=1.0;a+=0.1){
        String b=a+"F";
        Float f=Float.valueOf(b);
        this.setOpacity(f);
        try{
            Thread.sleep(100);
        }catch(Exception e){
            
        }}*/
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proceed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proceed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proceed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proceed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proceed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel namey;
    public javax.swing.JPanel paney;
    private javax.swing.JLabel pic;
    // End of variables declaration//GEN-END:variables
}
